### PR TITLE
not add space character for CJK 

### PR DESCRIPTION
**Pull request by napasa**

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks, quick style remarks:

- Please use consistent indentation (ideally, install formatSourceFiles.sh as a git pre-commit hook:

    cd .git/hooks
    ln -s ../../formatSourceFiles.sh

- The pull request should only contain relevant commits (not i.e. `Merge pull request #1 from manisandro/master  …`). Ideally, when developing a new feature, you branch of the current master, add your commits, and create the PR. If upstream has moved since you branched off, just `git rebase upstream/master` to rebase your new commits on top of the current master.

**Comment by napasa** [comment]
Thanks Sir! Your project let me learn a lot knowledge, thanks your dedication.

**Comment by napasa** [comment]
I try to rebase my new commit on top of your current master

**Comment by manisandro** [comment]
Right, and then just force-push to your branch, and you can keep using the previous PR.

**Comment by napasa** [comment]
WOW!!! Git is a amazing tool! I love it. I successfully rebase my current master to your remote repo master branch, Now I can read new commits committed after I fork your project..

ヽ(✿ﾟ▽ﾟ)ノ

**Pull request closed without merging**
