### PR TITLE
fix incomplete type 'QUrl' compile err in ubuntu 16.04

### PR DESCRIPTION
**Pull request by napasa**
when choose QT ui, Compile complain that Qurl is a imcomplete type.

### CODE REVIEW

**Comment by manisandro** [comment]
Thanks!

**Comment by napasa** [comment]
Hi,  I want to develop gImageReader together with you. But I am not familiar with unix development, Would you mind tell me what is your development envionment. Now I use QtCreator to open gImageReader top folder  to read source code and debug by attaching external program , Coz your project is not a purely Qt Project It could  not highlight source code normally, which will  slow My Read and debug speed and coding pleasure. Hahaha, So I need your help again.
  Thanks.

**Comment by manisandro** [comment]
That is likely a configuration issue on your end. I use pretty much vanilla qt-creator and just open it using the cmake project manager. You shouldn't need much else.

**Comment by napasa** [comment]
Thanks! I google it now

**Pull request merged**
