### PR TITLE
Add Traditional Chinese translations

### PR DESCRIPTION
**Pull request by timothytylee**
Translations for zh_TW and zh_HK have been added.  There is also a fix for auto-detection of Traditional Chinese in Config.cc.

### CODE REVIEW

**Comment by manisandro** [comment]
Thank you!

**Comment by manisandro** [comment]
By the way, do you want your name to be listed in the Translators section of the about dialog?

**Comment by timothytylee** [comment]
Sure!  :)

**Comment by manisandro** [comment]
OK done.

**Pull request merged**
