### PR TITLE
Choose PDF version during export

### PR DESCRIPTION
**Pull request by ZaMaZaN4iK**
Pull request about choosing PDF version during export.

It's not final version. I will ping you when all will be ready for merging.

### CODE REVIEW

**Comment by ZaMaZaN4iK** [comment]
Hmm, very interesting: i don't see any difference between PDF 1.0 and PDF 1.7 internally, except PDF version in a header.

**Comment by manisandro** [comment]
I don't really know that much about the PoDoFo internals, so I suppose one would need to have a look at the sourcecode to check what effect the version actually has.

**Comment by ZaMaZaN4iK** [comment]
Ok. Looks like that we use something from any modern PDF standard and PoDoFo simply ignore version. Also will be good idea to ask about it in PoDoFo mailing list or any IRC channel.

**Comment by ZaMaZaN4iK** [comment]
> On Wed, 2017-10-25 at 01:14 +0300, Alexander Zaitsev wrote:
> I create some document with different PDF versions and compared it 
> binary. What i saw: documents are identical inside, except PDF
> version in a PDF header.
>
>	Hi,
>as far as I can tell (and after grep of the code for GetPdfVersion()
>usages), there is not done any checking of the version when writing the
>output, it's left up to the user to not use primitives which cannot be
>used in the version the user chose.
>	Bye, zyx

Accoring to the letter, We should specify PDF writer for every PDF version. E.g. if you want to work with PDF 1.0 we can't use PDF streams, etc.

I think there are a lot of work here, so i don't know is it reasonable or not do it right now.

**Comment by manisandro** [comment]
Abandoned for the time being.

**Pull request closed without merging**
