### PR TITLE
[GTK] Rearrange and add missing icons

### PR DESCRIPTION
**Pull request by AvtechScientific**

### CODE REVIEW

**Comment by manisandro** [comment]
In your fork, please do

    git remote add upstream https://github.com/manisandro/gImageReader.git
    git fetch uptream
    git rebase upstream/master

to cleanup your commits.

**Comment by AvtechScientific** [comment]
well, this causes quite a lot of conflicts... should I first reset my fork several commits back (to the commit I've started to work)... then fetch/rebase and then commit?

I'm sorry, I'm not yet that well in git-fu :-)...

**Comment by AvtechScientific** [comment]
Also another point... I'm not sure, but shouldn't [this line](https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh#L159) come before [this line](https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh#L97)?... Otherwise you'll overwrite [GTK icons](https://github.com/manisandro/gImageReader/blob/master/packaging/win32/makeinstaller.sh#L114) with Qt icons (as it is currently the case)... or am I wrong?...

**Comment by manisandro** [comment]
You'll indeed want to rearrange those lines, I'd suggest moving

    cp -R $win32dir/gtk_skel/* $installroot

after

    cp -R $win32dir/skel/* $installroot

and enclose it in `if [ "$iface" == "gtk" ]; then`

**Pull request closed without merging**
