### PR TITLE
Fix some issues reported by LGTM

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
While the first commit is uncritical, the second one needs a closer review. I think that the "suggestions" from LGTM discovered code bugs.

**Comment by manisandro** [comment]
Thanks! Could you apply these changes also to the Qt interface?

**Comment by stweil** [comment]
The first commit is only valid for GTK. The second commit fixes GTK and Qt.

**Comment by manisandro** [comment]
Ah missed the Qt change, ok perfect, thanks!

**Pull request merged**
