### PR TITLE
Fixes #521

### LINKED ISSUE #521: GTK: multiple tabs
It would be nice to have multiple tabs in the GTK OutputEditor. This way you can output different parts of recognized text to different tabs, play with settings to achieve better results and then compare the output in different tabs, etc..

Tabs can be horizontal, like in Gedit and [GtkNotebook widget](https://developer.gnome.org/gtk3/stable/GtkNotebook.html) can be used:

Screenshot from 2021-05-24 18-49-01

### PR DESCRIPTION
**Pull request by AvtechScientific**
Adds multi tabs to the OutputTextEditor; makes it  visible by default on app launch so everything is ready for editor's work straight away thus switching focus from input to output (reasoning behind the change - gImageReader is an OCR tool, not a pdf viewer).
Updates translations.

### CODE REVIEW

**Comment by AvtechScientific** [comment]
Hi @manisandro ! Any chance to merge this PR? It starts to produce conflicts in translations... (they are trivial though to fix)...

**Comment by manisandro** [comment]
Sorry - can you rebase once more, then I'll merge immediately!

**Comment by AvtechScientific** [comment]
@manisandro - done.

**Comment by manisandro** [comment]
thanks!

**Pull request merged**
