### PR TITLE
Run OpenMP once before calling tesseract (fixes: #285)

### PR DESCRIPTION
**Pull request by innir**

### CODE REVIEW

**Comment by napasa** [comment]
It is not compatible to MingGW

**Comment by manisandro** [comment]
@innir Is this still necessary on your setup?

**Comment by innir** [comment]
Yes, it's still needed :-(
[Though I used gimagereader 3.2.3 to test it]
[Using tessdata_fast training data]

**Comment by manisandro** [comment]
I've never seen this again with recent tesseract 4.x and 5.x, feel free to reopen if still relevant.

**Pull request closed without merging**
